### ISSUE TITLE
Can't create Taxonomy with Spree 4.4

### ISSUE THREAD

**Issue by Kulgar** [mrbrdo/spree_mobility#6]
Hello again :-)

I faced a new issue today: I'm no longer able to create new taxonomies.

After some digging, I found that the culprit is that line : 

```
validates :name, presence: true
```

In the taxon_decorator.rb file. 

Indeed, when we create a new Taxonomy, it automatically creates a new taxon : 

```
# from spree core

    after_create :set_root
    after_save :set_root_taxon_name

    private

    def set_root
      self.root ||= Taxon.create!(taxonomy_id: id, name: name)
    end

    def set_root_taxon_name
      return unless saved_change_to_name?
      return if name.to_s == root.name.to_s

      root.update(name: name)
    end
```

In Spree 4.4, the Taxon name validation is this: 

```
    validates :name, presence: true, uniqueness: { scope: [:parent_id, :taxonomy_id], allow_blank: true, case_sensitive: false }
```

I don't really have time to investigate more... but, right now, deactivating the validates in the decorator fixes my problem. 
Do you have any idea on a possible fix? 

Thx!

**Comment by mrbrdo** [comment]
I can immediately confirm this as I had the same problem on a new Spree (5.alpha) project.
I came to the exact same code in spree core as you did, and after some time I was not able to exactly figure out what is going on. I think the issue is related to mobility itself (not spree_mobility). The interaction between those 2 after_create/save hooks and mobility makes it so the name is not correctly read from translations, but instead from the main table where it is nil (which is normally fine). As far as why it happens I'm not sure at this point, but I have a feeling it's a bug/issue in mobility gem.

**Comment by mrbrdo** [comment]
@Kulgar okay so I figured out what's going on. Another hook was added in 4.4.x to Taxon, which triggers before Taxonomy translation is created in DB. Although possibly mobility can be improved for such situation to not be a problem, avoiding unnecessary hook on create fixes it. I fixed this in https://github.com/mrbrdo/spree/commit/71d42efdf418302cda5bb21c1f8453d9aee2bcc9 on my 4_4_fixes branch of spree (which is actually 5.alpha).

**Comment by Kulgar** [comment]
@mrbrdo : thanks for the investigation! 

Weird, as I did solve / fix the bug by just commenting this line in spree mobility decorator: 

https://github.com/mrbrdo/spree_mobility/blob/0ec8da801d3307ccec57c65c8cf698af36f87eb1/lib/spree_mobility/core_ext/spree/taxon_decorator.rb#L44

I didn't have to patch Spree 4.4 in any way to make it work...

**Comment by mrbrdo** [comment]
Yeah, but now you don't have validation on the name. Which means you can save a Taxon with an empty name, but that shouldn't be allowed.

**Comment by Kulgar** [comment]
ok, understood, but patching Spree isn't an option for me right now :-)

**Comment by mrbrdo** [comment]
@Kulgar spree just merged the fix into main branch:
https://github.com/spree/spree/pull/11705#event-7691049345

**Comment by Kulgar** [comment]
nice, thanks @mrbrdo
